fileversion: 3

robots:
  cf6:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E7E6
    initial_position: [0.5, 0.5, 0.0]
    type: cf21

  cf7:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E7E7
    initial_position: [0.5, 3.0, 0.0]
    type: cf21

  cf8:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E7E8
    initial_position: [0.5, 5.5, 0.0]
    type: cf21

robot_types:
  cf21:
    motion_capture:
      tracking: "librigidbodytracker"
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7

all:
  firmware_logging:
    enabled: true
    default_topics:
      pose:
        frequency: 20
      status:
        frequency: 2

  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2
      controller: 2
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1

  reference_frame: "world"

  broadcasts:
    num_repeats: 15
    delay_between_repeats_ms: 1